### ISSUE TITLE
Add font-smoothing

### ISSUE THREAD

**Issue by tiaanduplessis** [tiaanduplessis/nanoreset#1]
`-webkit-font-smoothing: antialiased;`
`-moz-osx-font-smoothing: grayscale;`

**Comment by tiaanduplessis** [comment]
```css
body {
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```
